import "./globals.css";
import "aos/dist/aos.css";
import { AuthProvider } from "@/context/AuthContext";
import Navbar from "@/components/Navigition/Navbar";
import Footer from "@/components/Navigition/Footer";

export const metadata = {
  title: "Home - Yourdes.vercel.app",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html dir="rtl" lang="ar">
      <body className="flex flex-col min-h-screen max-w-screen-2xl mx-auto">
        <AuthProvider>
          <Navbar/>
          <main className="relative overflow-hidden flex-1">
        {children}
          </main>
          <Footer/>
        </AuthProvider>
      </body>
    </html>
  );
}
